### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by niallthompson** [lindseydiloreto/craft-languagelink#1]
When I try any of the examples given in the docs I get the following error:

Internal Server Error

array_key_exists() expects parameter 2 to be array, null given

Any thoughts as to why this is happening?

**Comment by lindseydiloreto** [comment]
Hey Niall,

When you configure a site with multiple locales, it's expected that your `siteUrl` config value will be an array. Each key should map to a specific locale. See Step #4 for more details...

http://buildwithcraft.com/docs/localization-guide#step-4-define-your-site-uRLs

I'll go ahead and build in a safeguard so that the plugin fails more gracefully if that value is not an array. Thanks for the heads up!

**Comment by lindseydiloreto** [comment]
I've updated the plugin, feel free to grab the latest version! :)

Be sure to also change your `siteUrl` to an array, since that is technically the intended configuration.
