### ISSUE TITLE
No Releases Despite Being on Version 1.1.0

### ISSUE THREAD

**Issue by wesleyb-phmgmt** [lindseydiloreto/craft-languagelink#10]
The commit [(v1.1.0) Compatible with Craft 2.5](https://github.com/lindseydiloreto/craft-languagelink/commit/08bacb0c9f531fa805db58c470761380c73e87cc) on `master` branch suggests that the plugin is at version `1.1.0`, but there is no release branch for this version. A release branch allows a user of a plugin to easily pin their installed version, and allows the developre to distinguish releases publicly in an expected manner. An example of this is available in the repository for for the plugin [HTML Cache](https://github.com/craftapi/htmlcache/releases).

**Comment by lindseydiloreto** [comment]
I'm not sure what the question is... The `master` branch is on v1.1.0.

**Comment by wesleyboar-fka-iosulfur** [comment]
When one visits the [release page](https://github.com/lindseydiloreto/craft-languagelink/releases) for a GitHub project it is either has 0 releases, or some releases. I don't really know how to make that happen nor do I know if it has any technical benefit _(the user benefit is being able to browse releases through the GitHub website user interface)_. The `craft-languagelink` project may have a 1.1.0 release _(great job, by the way)_, but it doesn't show as a release on the "Releases" page.

**Comment by lindseydiloreto** [comment]
Hey Wesley,

I know this is an old thread, but I _finally_ grasp the importance of releases. After porting a handful of plugins to Craft 3, it's become much clearer. Since Craft 3 uses Composer, it's critical for me to **tag** each release with a version number.

Once I've ported this plugin to Craft 3 (hopefully by the end of January or February), then I'll begin tagging each release. I can't promise that I'll go back and tag old releases, but I'll certainly keep tagging them moving forward.

Thanks for enlightening me! 😃

**Comment by wesleyboar-fka-iosulfur** [comment]
You're welcome. 😃
